# first makefile
source = 01_hello_SDL.cpp

# output
output = 01_hello_SDL

# command
command = g++

# compiler flags -w suppresses warnings
compiler_flag = -w

# linker flags using sdl lib
linker_flag = -lSDL2

all: $(source)
	$(command) $(source) $(compiler_flag) $(linker_flag) -o $(output)