### EXCERCISE TABLE ### \
ec1 	|	make max_rows & data a value that can be changed

flags = -Wall -g
no_dbg = -DNDEBUG
# default file and output
filename = ex23.c
main_output = ex23

clean:
	rm $(main_output)
extra-credit:
	# extra credit commands
build:
	gcc $(flags) $(filename) -o $(main_output)
debug:
	gcc $(flags) $(filename) -o $(main_output)
all:
	gcc $(flags) $(no_dbg) $(filename) -o $(main_output)

no_wall:
	gcc $(filename) -o $(main_output)
