### EXCERCISE TABLE ### \
ec1 	|	make max_rows & data a value that can be changed

flags = -Wall -g
# default file and output
filename = ex19.c
main_output = ex19

clean:
	rm $(main_output)
extra-credit:
	# extra credit commands
build:
	gcc $(flags) $(filename) -o $(main_output)
all:
	gcc $(flags) $(filename) -o $(main_output)
